### ISSUE TITLE
ChatGPT Api 구현, MyPage 데이터 연결

### ISSUE THREAD

**Issue by pooya98** [pooya98/ninemova#36]
## descriptions
- ChatGPT Api 구현
- MyPage ViewModel 생성
- MyPage 데이터 연결

## TODO
- [x] ChatGPT Api retrofit 설정
- [x] ChatGPT Api Request, Api Response 객체 생성
- [x] ChatGPT Repsoitory 생성
- [x] MyPage ViewModel 생성
- [x] PieChart와 데이터 연결 (Binding Adapter 추가)
