### ISSUE TITLE
ChatGPT 영화 추천 기능 구현

### ISSUE THREAD

**Issue by pooya98** [pooya98/ninemova#40]
## descriptions
- ChatGPT 영화 추천 기능 구현

## TODO
- [x] RecommendFragment UI 수정 
- [x] RecommendFragment ViewModel 생성 및 연결
- [x] 영화 추천 프롬프트 생성
