### ISSUE TITLE
Home UI 수정 및 기능 구현

### ISSUE THREAD

**Issue by pooya98** [pooya98/ninemova#50]
## descriptions
- Home UI 수정
- HomeViewModel, HomeUiState, HomeViewEvent 생성 및 구현
- HomeFragement 데이터 연결

## TODO
- [x] TMDB Api 추가 (인기영화 리스트 가져오기, 상영중인 영화 리스트 가져오기)
- [x] Home UI 수정
- [x] HomeViewModel, HomeUiState, HomeViewEvent 생성 및 구현
- [x] HomeFragement 데이터 연결
